const f =()=>{

    try{
        let a = 0
        // console.log(program);
        console.log('Program run successfully');
        return
    }
    catch(err){
        console.log("This is an error");
        console.log(p);
    }
    finally{  
        //for final clean up
        console.log('I am a good boy');
        // close the file
        // Exit the loop
        // write to log file
    }
}

f()

console.log('End');